# Generated by Django 2.1.4 on 2020-06-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
                ('pol_party', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(max_length=200, verbose_name='response')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Question')),
            ],
        ),
    ]
