# Generated by Django 2.1.4 on 2020-06-30 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='office',
        ),
        migrations.AddField(
            model_name='candidate',
            name='fname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to Page'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lname',
            field=models.CharField(max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pol_office',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Political Office'),
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pol_party',
            field=models.CharField(blank=True, choices=[('AMER1ST', 'America First Party'), ('COMM', 'Communist Party'), ('CONST', 'Constitution Party'), ('DEM', 'Democratic party'), ('PATR', 'American Patriot Party'), ('GREEN', 'Green Party'), ('MARYJ', 'Marijuana Party'), ('LIB', 'Libertarion Party'), ('REF', 'Reform Party'), ('REP', 'Republican Party'), ('SOC', 'Socialist Labor Party'), ('UNI', 'Unity Party')], max_length=200, null=True, verbose_name='Political Party'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='response'),
        ),
    ]
